const {
  VITE_AVATARS_COLLECTION_NAME,
  VITE_USERS_COLLECTION_NAME,
  VITE_UPLOAD_PRESET,
  VITE_UPLOAD_URL,
  VITE_AVATARS_PATH,
  VITE_BOARDS_COLLECTION_NAME,
  VITE_USER_BOARDS_COLLECTION_NAME,
  VITE_BOARDS_TEMPLATE_COLLECTION_NAME,
  VITE_COLUMNS_COLLECTION_NAME,
} = import.meta.env;

export const AVATARS_COLLECTION_NAME = VITE_AVATARS_COLLECTION_NAME;
export const USERS_COLLECTION_NAME = VITE_USERS_COLLECTION_NAME;
export const UPLOAD_PRESET = VITE_UPLOAD_PRESET;
export const UPLOAD_URL = VITE_UPLOAD_URL;
export const AVATARS_PATH = VITE_AVATARS_PATH;
export const BOARDS_COLLECTION_NAME = VITE_BOARDS_COLLECTION_NAME;
export const USER_BOARDS_COLLECTION_NAME = VITE_USER_BOARDS_COLLECTION_NAME;
export const BOARDS_TEMPLATE_COLLECTION_NAME = VITE_BOARDS_TEMPLATE_COLLECTION_NAME;
export const COLUMNS_COLLECTION_NAME = VITE_COLUMNS_COLLECTION_NAME;

export enum PATHS {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  FORGOT_PASSWORD = '/forgot-password',
  PROFILE = '/profile',
  BOARD = '/board',
}