import { TASK_PRIORITY_TEXT } from '@store';

export const TASK_PRIORITY_COLORS = {
  [TASK_PRIORITY_TEXT.HIGH]: '#FF9800',
  [TASK_PRIORITY_TEXT.LOW]: '#64B5F6',
  [TASK_PRIORITY_TEXT.MEDIUM]: '#FFEB3B',
  [TASK_PRIORITY_TEXT.URGENT]: '#D32F2F',
};
