import { TASK_PRIORITY } from '@store';

export const TASK_PRIORITY_COLORS = {
  [TASK_PRIORITY.HIGH]: '#FF9800',
  [TASK_PRIORITY.LOW]: '#64B5F6',
  [TASK_PRIORITY.MEDIUM]: '#FFEB3B',
  [TASK_PRIORITY.URGENT]: '#D32F2F',
};
